name: tomato_disease_detection1
description: Tomato Disease Detection an android app that uses machine learning techniques to detection classify Tomato Disease.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  image: ^3.0.2
  path_provider: ^2.0.0
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/withunknown1.tflite
  - assets/labels.txt
  - assets/splash1.png
  - assets/classes/